# Generated by Django 2.0.7 on 2018-09-03 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=500, verbose_name='Company, Business, or Project name')),
                ('tagline', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Tagline')),
                ('address', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Business address')),
                ('phone_number', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Phone Number')),
                ('email', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Email')),
                ('website', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Website')),
                ('presented_to', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Presented to')),
                ('logo', models.ImageField(default='logo_default.png', null=True, upload_to='imgs/', verbose_name='Logo')),
                ('main_content', models.TextField(blank=True, default='', null=True, verbose_name='Main Content')),
                ('financial_assumptions', models.TextField(blank=True, default='', null=True, verbose_name='Financial Assumptions')),
                ('financial_input', models.TextField(blank=True, default='', null=True, verbose_name='Financial Input')),
                ('rpt_pnl', models.TextField(blank=True, default='', null=True, verbose_name='Monthly P&L')),
                ('rpt_amortization', models.TextField(blank=True, default='', null=True, verbose_name='Monthly Amortization')),
                ('rpt_cash_flow', models.TextField(blank=True, default='', null=True, verbose_name='Cash Flow')),
                ('rpt_balance_sheet', models.TextField(blank=True, default='', null=True, verbose_name='Balance Sheet')),
                ('rpt_dashboard', models.TextField(blank=True, default='', null=True, verbose_name='Dashboard')),
                ('size', models.FloatField(blank=True, default=0, null=True, verbose_name='Size')),
                ('date_created', models.DateTimeField(blank=True, null=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(blank=True, null=True, verbose_name='Date Modified')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Business Plan Owner')),
            ],
            options={
                'verbose_name': 'Business Plan',
                'verbose_name_plural': 'Business Plans',
                'ordering': ['-date_modified', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Codes')),
                ('full_name', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('rate_to_dollar', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Rate to Dollar')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='HelpSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Ref Id')),
                ('title', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Help Section Title')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Desription')),
            ],
            options={
                'verbose_name': 'Help Section',
                'verbose_name_plural': 'Help Sections',
                'ordering': ['ref_id'],
            },
        ),
        migrations.CreateModel(
            name='HelpSubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Help Sub-Section Title')),
                ('instruction', models.TextField(blank=True, default='', null=True, verbose_name='Instruction')),
                ('help_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_help_sections', to='bplanner.HelpSection', verbose_name='Help Section')),
            ],
            options={
                'verbose_name': 'Help Sub-Section',
                'verbose_name_plural': 'Help Sub-Sections',
            },
        ),
        migrations.CreateModel(
            name='HelpSubSectionExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Example Title')),
                ('example', models.TextField(blank=True, default='', null=True, verbose_name='Example')),
                ('help_sub_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_help_sub_section_examples', to='bplanner.HelpSubSection', verbose_name='Help Sub-Section')),
            ],
            options={
                'verbose_name': 'Help Sub-Section Example',
                'verbose_name_plural': 'Help Sub-Section Examples',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Codes')),
                ('full_name', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('order', models.FloatField(blank=True, default=0, null=True, verbose_name='Month order')),
            ],
            options={
                'verbose_name': 'Month',
                'verbose_name_plural': 'Months',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.FloatField(blank=True, default=0, null=True, verbose_name='Space Used')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
