# Generated by Django 2.0.7 on 2018-09-07 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bplanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPlanFinancialAssumptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.IntegerField(blank=True, default=0, max_length=500, null=True, verbose_name='Currency')),
                ('first_financial_year', models.IntegerField(blank=True, null=True, verbose_name='First Financial Year')),
                ('first_financial_year_month', models.CharField(blank=True, max_length=500, null=True, verbose_name='Month of starting operations')),
                ('projection_years', models.IntegerField(blank=True, null=True, verbose_name='Period of Projections in Years')),
                ('offerings_products_or_services', models.CharField(blank=True, default=0, max_length=500, null=True, verbose_name='Products/Services')),
                ('number_of_products_or_services', models.CharField(blank=True, default=1, max_length=500, null=True, verbose_name='Number of Products or Services Offered ')),
                ('product_services_table', models.TextField(blank=True, default='', null=True, verbose_name='Products or Services Offered Table')),
                ('count_of_months_in_financial_year', models.IntegerField(blank=True, default=12, null=True, verbose_name='Number of Months in Projection Year')),
                ('inflation_rate', models.FloatField(blank=True, default=0, null=True, verbose_name='Inflation Rate (Per Annum)')),
                ('salary_growth_rate', models.FloatField(blank=True, default=0, null=True, verbose_name='Salary Growth Rate (Per Annum)')),
                ('amortization_period', models.IntegerField(blank=True, null=True, verbose_name='Startup Cost Amortization Period (in Years) ')),
                ('trade_receivables', models.IntegerField(blank=True, null=True, verbose_name='Trade Receivables (period in months)')),
                ('trade_payables', models.IntegerField(blank=True, null=True, verbose_name='Trade Payables (period in months)')),
                ('other_expenses_payables', models.IntegerField(blank=True, null=True, verbose_name='Other Expenses Payable')),
                ('bad_debts', models.FloatField(blank=True, null=True, verbose_name='Bad Debts (% of revenue)')),
                ('taxation_system', models.IntegerField(blank=True, default=0, null=True, verbose_name='Taxation System')),
                ('corporate_tax_rate', models.FloatField(blank=True, default=20, null=True, verbose_name='Corporate Tax Rate ')),
                ('tax_slabs_table', models.TextField(blank=True, default='', max_length=500, null=True, verbose_name='Tax Slabs')),
                ('size', models.FloatField(blank=True, default=0, null=True, verbose_name='Size')),
                ('date_created', models.DateTimeField(blank=True, null=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(blank=True, null=True, verbose_name='Date Modified')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Business Plan Owner')),
            ],
            options={
                'verbose_name': 'Business Plan FinancialAssumptions',
                'verbose_name_plural': 'Business Plans FinancialAssumptions',
                'ordering': ['-date_modified', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPlanFinancialDataInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_input', models.TextField(blank=True, default='', null=True, verbose_name='Financial Input')),
                ('size', models.FloatField(blank=True, default=0, null=True, verbose_name='Size')),
                ('date_created', models.DateTimeField(blank=True, null=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(blank=True, null=True, verbose_name='Date Modified')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Business Plan Owner')),
            ],
            options={
                'verbose_name': 'Business Plan Financial Data Input',
                'verbose_name_plural': 'Business Plans Financial Data Input',
                'ordering': ['-date_modified', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPlanMainContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_content', models.TextField(blank=True, default='', null=True, verbose_name='Main Content')),
                ('size', models.FloatField(blank=True, default=0, null=True, verbose_name='Size')),
                ('date_created', models.DateTimeField(blank=True, null=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(blank=True, null=True, verbose_name='Date Modified')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Business Plan Owner')),
            ],
            options={
                'verbose_name': 'Business Plan Main Content',
                'verbose_name_plural': 'Business Plans Main Content',
                'ordering': ['-date_modified', '-date_created'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPlanTitlePage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='', max_length=500, verbose_name='Company, Business, or Project name')),
                ('tagline', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Tagline')),
                ('address', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Business address')),
                ('phone_number', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Phone Number')),
                ('email', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Email')),
                ('website', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Website')),
                ('presented_to', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Presented to')),
                ('logo', models.ImageField(default='logo_default.png', null=True, upload_to='imgs/', verbose_name='Logo')),
                ('size', models.FloatField(blank=True, default=0, null=True, verbose_name='Size')),
                ('bplan_size', models.FloatField(blank=True, default=0, null=True, verbose_name='Size')),
                ('date_created', models.DateTimeField(blank=True, null=True, verbose_name='Date Created')),
                ('date_modified', models.DateTimeField(blank=True, null=True, verbose_name='Date Modified')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Business Plan Owner')),
            ],
            options={
                'verbose_name': 'Business Plan Title Page',
                'verbose_name_plural': 'Business Plans Title Page',
                'ordering': ['-date_modified', '-date_created'],
            },
        ),
        migrations.RemoveField(
            model_name='businessplan',
            name='owner',
        ),
        migrations.DeleteModel(
            name='BusinessPlan',
        ),
        migrations.AddField(
            model_name='businessplanmaincontent',
            name='title_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bplanner.BusinessPlanTitlePage', verbose_name='Business Plan Title Page'),
        ),
        migrations.AddField(
            model_name='businessplanfinancialdatainput',
            name='title_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bplanner.BusinessPlanTitlePage', verbose_name='Business Plan Title Page'),
        ),
        migrations.AddField(
            model_name='businessplanfinancialassumptions',
            name='title_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bplanner.BusinessPlanTitlePage', verbose_name='Business Plan Title Page'),
        ),
    ]
