# Generated by Django 2.0.7 on 2018-09-10 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0002_auto_20180907_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPlanSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_monitor', models.TextField(blank=True, default='', null=True, verbose_name='Step Monitor')),
                ('calendarMonths', models.TextField(blank=True, default='', null=True, verbose_name='Step Monitor')),
                ('projectionMonthsList', models.TextField(blank=True, default='', null=True, verbose_name='Step Monitor')),
                ('projectionYears', models.IntegerField(blank=True, default=0, null=True, verbose_name='Number of projection years')),
                ('first_financial_year', models.IntegerField(blank=True, default=2018, null=True, verbose_name='First Financial Year')),
                ('last_financial_year', models.IntegerField(blank=True, null=True, verbose_name='Last Financial Year')),
                ('count_of_months_in_financial_year', models.IntegerField(blank=True, default=12, null=True, verbose_name='Count of months in a financial year')),
                ('projection_years_list', models.TextField(blank=True, default='[]', null=True, verbose_name='Projection years list')),
                ('product_count', models.IntegerField(blank=True, null=True, verbose_name='Products/Services count')),
                ('products', models.TextField(blank=True, default='', null=True, verbose_name='Step Monitor')),
                ('theme', models.TextField(blank=True, default='', null=True, verbose_name='Theme')),
                ('cost_appropriation_methods', models.TextField(blank=True, default='', null=True, verbose_name='Cost Appropriation Methods')),
                ('operating_cost_list', models.TextField(blank=True, default='', null=True, verbose_name='Operating Costs List')),
                ('employees_list', models.TextField(blank=True, default='', null=True, verbose_name='Employees List')),
                ('capital_sources_list', models.TextField(blank=True, default='', null=True, verbose_name='Capital Sources List')),
                ('tangible_assets_list', models.TextField(blank=True, default='', null=True, verbose_name='Tangible Assets List')),
                ('intangible_assets_list', models.TextField(blank=True, default='', null=True, verbose_name='Intangible Assets List')),
                ('deposit_item_list', models.TextField(blank=True, default='', null=True, verbose_name='Deposit Items List')),
                ('startup_cost_item_list', models.TextField(blank=True, default='', null=True, verbose_name='Startup Cost Items List')),
                ('total_assets', models.TextField(blank=True, default='', null=True, verbose_name='Total Assets')),
                ('total_liabilities', models.TextField(blank=True, default='', null=True, verbose_name='Total Liabilities')),
                ('tangible_assets_balance_total', models.TextField(blank=True, default='', null=True, verbose_name='Tangible Assets Balance Total')),
                ('intangible_assets_balance_total', models.TextField(blank=True, default='', null=True, verbose_name='Intangible Assets Balance Total')),
                ('cashFlow_changes_during_the_year_per_month', models.TextField(blank=True, default='', null=True, verbose_name='Cash Flow Changes During The Year Per Month')),
                ('closing_cash_balance_per_month', models.TextField(blank=True, default='', null=True, verbose_name='Closing Cash Balance Per Month')),
                ('revenue_totals_per_year', models.TextField(blank=True, default='', null=True, verbose_name='Revenue Totals Per Year')),
                ('direct_cost_totals_per_year', models.TextField(blank=True, default='', null=True, verbose_name='Direct Cost Totals Per Year')),
                ('gross_profit', models.TextField(blank=True, default='', null=True, verbose_name='Gross Profit')),
                ('operating_cost_totals_per_year', models.TextField(blank=True, default='', null=True, verbose_name='Operating Cost Totals Per Year')),
                ('eat', models.TextField(blank=True, default='', null=True, verbose_name='EAT')),
                ('net_margin_per_month', models.TextField(blank=True, default='', null=True, verbose_name='Net Margin Per Month')),
            ],
            options={
                'verbose_name': 'Business Plan Settings',
                'verbose_name_plural': 'Business Plans Settings',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterField(
            model_name='businessplanfinancialassumptions',
            name='currency',
            field=models.IntegerField(choices=[(0, 'USD'), (1, 'POUND'), (2, 'EURO')], default=0, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='businessplanfinancialassumptions',
            name='number_of_products_or_services',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Number of Products or Services Offered '),
        ),
        migrations.AlterField(
            model_name='businessplanfinancialassumptions',
            name='offerings_products_or_services',
            field=models.IntegerField(choices=[(0, 'Products'), (1, 'Services')], default=0, verbose_name='Products/Services'),
        ),
        migrations.AlterField(
            model_name='businessplanfinancialassumptions',
            name='taxation_system',
            field=models.IntegerField(choices=[(0, 'Slab System'), (1, 'Single System')], default=0, verbose_name='Taxation System'),
        ),
        migrations.AlterField(
            model_name='businessplanmaincontent',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Business Plan Owner'),
        ),
        migrations.AlterField(
            model_name='businessplanmaincontent',
            name='title_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bplanner.BusinessPlanTitlePage', verbose_name='Business Plan Title Page'),
        ),
        migrations.AlterField(
            model_name='businessplantitlepage',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Company, Business, or Project name'),
        ),
        migrations.AlterField(
            model_name='businessplantitlepage',
            name='logo',
            field=models.ImageField(blank=True, default='logo_default.png', null=True, upload_to='imgs/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='businessplantitlepage',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Business Plan Owner'),
        ),
        migrations.AddField(
            model_name='businessplansettings',
            name='title_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bplanner.BusinessPlanTitlePage', verbose_name='Business Plan Title Page'),
        ),
    ]
