# Generated by Django 2.0.7 on 2018-09-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0003_auto_20180910_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessplansettings',
            old_name='calendarMonths',
            new_name='calendar_months',
        ),
        migrations.RenameField(
            model_name='businessplansettings',
            old_name='projectionMonthsList',
            new_name='projection_months_list',
        ),
        migrations.RenameField(
            model_name='businessplansettings',
            old_name='projectionYears',
            new_name='projection_years',
        ),
    ]
