# Generated by Django 2.0.7 on 2018-09-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0004_auto_20180910_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplanfinancialassumptions',
            name='bad_debts',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Bad Debts (% of revenue)'),
        ),
        migrations.AlterField(
            model_name='businessplanfinancialassumptions',
            name='inflation_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Inflation Rate (Per Annum)'),
        ),
        migrations.AlterField(
            model_name='businessplanfinancialassumptions',
            name='number_of_products_or_services',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Products or Services Offered '),
        ),
        migrations.AlterField(
            model_name='businessplanfinancialassumptions',
            name='salary_growth_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='Salary Growth Rate (Per Annum)'),
        ),
        migrations.AlterField(
            model_name='businessplanfinancialassumptions',
            name='tax_slabs_table',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Tax Slabs'),
        ),
    ]
