# Generated by Django 2.0.7 on 2018-09-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0005_auto_20180911_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplanfinancialassumptions',
            name='corporate_tax_rate',
            field=models.IntegerField(blank=True, default=20, null=True, verbose_name='Corporate Tax Rate '),
        ),
        migrations.AlterField(
            model_name='businessplanfinancialassumptions',
            name='inflation_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Inflation Rate (Per Annum)'),
        ),
        migrations.AlterField(
            model_name='businessplanfinancialassumptions',
            name='salary_growth_rate',
            field=models.IntegerField(blank=True, null=True, verbose_name='Salary Growth Rate (Per Annum)'),
        ),
    ]
