# Generated by Django 2.0.7 on 2018-09-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0006_auto_20180911_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplanfinancialassumptions',
            name='tax_slabs_table',
            field=models.TextField(blank=True, null=True, verbose_name='Tax Slabs'),
        ),
    ]
