# Generated by Django 2.0.7 on 2018-09-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0007_auto_20180911_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessplanmaincontent',
            name='main_content',
        ),
        migrations.RemoveField(
            model_name='businessplanmaincontent',
            name='title_page',
        ),
        migrations.AddField(
            model_name='businessplanmaincontent',
            name='company_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Company Description'),
        ),
        migrations.AddField(
            model_name='businessplanmaincontent',
            name='executive_summary',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Executive Summary'),
        ),
        migrations.AddField(
            model_name='businessplanmaincontent',
            name='industry_analysis',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Industry Analysis'),
        ),
        migrations.AddField(
            model_name='businessplanmaincontent',
            name='insights',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Insights'),
        ),
        migrations.AddField(
            model_name='businessplanmaincontent',
            name='key_success_factors',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Key Success Factors'),
        ),
        migrations.AddField(
            model_name='businessplanmaincontent',
            name='marketing_plan',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Marketing Plan'),
        ),
        migrations.AddField(
            model_name='businessplanmaincontent',
            name='milestones',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Milestones'),
        ),
        migrations.AddField(
            model_name='businessplanmaincontent',
            name='mission_vision',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Mission and Vision'),
        ),
        migrations.AddField(
            model_name='businessplanmaincontent',
            name='objectives',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Objectives'),
        ),
        migrations.AddField(
            model_name='businessplanmaincontent',
            name='ownership_and_management_plan',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Ownership and Management Plan'),
        ),
        migrations.AddField(
            model_name='businessplanmaincontent',
            name='swot_analysis',
            field=models.TextField(blank=True, default='', null=True, verbose_name='SWOT Analysis'),
        ),
        migrations.AddField(
            model_name='businessplanmaincontent',
            name='tam_sam_som_analysis',
            field=models.TextField(blank=True, default='', null=True, verbose_name='TAM-SAM-SOM Analysis'),
        ),
    ]
