# Generated by Django 2.0.7 on 2018-09-24 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0008_auto_20180924_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessplanmaincontent',
            name='title_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bplanner.BusinessPlanTitlePage', verbose_name='Business Plan Title Page'),
        ),
    ]
