# Generated by Django 2.0.7 on 2018-10-01 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0009_businessplanmaincontent_title_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPlanSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='Display Name')),
                ('business_types', models.IntegerField(choices=[(0, 'Non-Profit'), (1, 'For Profit')], default=1, verbose_name='Business Type')),
                ('title_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bplanner.BusinessPlanTitlePage', verbose_name='Business Plan Title Page')),
            ],
            options={
                'verbose_name': 'Business Plan Sample',
                'verbose_name_plural': 'Business Plans Samples',
            },
        ),
        migrations.AlterField(
            model_name='businessplanfinancialassumptions',
            name='taxation_system',
            field=models.IntegerField(choices=[(0, 'Tiered System'), (1, 'Single System')], default=0, verbose_name='Taxation System'),
        ),
    ]
