# Generated by Django 2.0.7 on 2018-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0010_auto_20181001_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplantitlepage',
            name='logo',
            field=models.ImageField(blank=True, default='/imgs/logo_default.png', null=True, upload_to='imgs/', verbose_name='Logo'),
        ),
    ]
