# Generated by Django 2.0.7 on 2018-10-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0013_auto_20181004_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessplansettings',
            name='month_list_initiated',
            field=models.CharField(blank=True, default='false', max_length=10, null=True, verbose_name='Month List Initiated'),
        ),
    ]
