# Generated by Django 2.0.7 on 2018-10-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0014_businessplansettings_month_list_initiated'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessplansettings',
            name='year_list_initiated',
            field=models.BooleanField(default=False, verbose_name='Year List Initiated'),
        ),
        migrations.AlterField(
            model_name='businessplansettings',
            name='month_list_initiated',
            field=models.BooleanField(default=False, verbose_name='Month List Initiated'),
        ),
    ]
