# Generated by Django 2.0.7 on 2018-10-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0017_auto_20181005_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplanfinancialassumptions',
            name='first_financial_year_month',
            field=models.IntegerField(default=1, verbose_name='Month Index of starting operations'),
        ),
    ]
