# Generated by Django 2.0.7 on 2018-07-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Help Titles')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Desription')),
            ],
        ),
        migrations.CreateModel(
            name='HelpSubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Help Sub-Section Titles')),
            ],
        ),
        migrations.CreateModel(
            name='HelpSubSectionExample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Help Sub-Section Example Titles')),
            ],
        ),
    ]
