# Generated by Django 2.0.7 on 2018-07-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='help',
            options={'verbose_name': 'Help Content', 'verbose_name_plural': 'Help Contents'},
        ),
        migrations.AlterModelOptions(
            name='helpsubsection',
            options={'verbose_name': 'Help Sub-Section', 'verbose_name_plural': 'Help Sub-Sections'},
        ),
        migrations.AlterModelOptions(
            name='helpsubsectionexample',
            options={'verbose_name': 'Help Sub-Section Example', 'verbose_name_plural': 'Help Sub-Section Examples'},
        ),
        migrations.AddField(
            model_name='help',
            name='ref_id',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Ref Ids'),
        ),
    ]
