# Generated by Django 2.0.7 on 2018-07-23 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0003_auto_20180723_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpsubsectionexample',
            name='help_sub_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bplanner.HelpSubSection', verbose_name='Help Sub-Sections'),
        ),
        migrations.AlterField(
            model_name='helpsubsection',
            name='title',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Help Sub-Section Title'),
        ),
    ]
