# Generated by Django 2.0.7 on 2018-07-23 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0004_auto_20180723_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Ref Id')),
                ('title', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Help Section Title')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Desription')),
            ],
            options={
                'verbose_name': 'Help Section Content',
                'verbose_name_plural': 'Help Section Contents',
                'ordering': ['ref_id'],
            },
        ),
        migrations.AlterField(
            model_name='helpsubsection',
            name='help',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bplanner.HelpSection', verbose_name='Help Section'),
        ),
        migrations.AlterField(
            model_name='helpsubsectionexample',
            name='help_sub_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bplanner.HelpSubSection', verbose_name='Help Sub-Section'),
        ),
        migrations.AlterField(
            model_name='helpsubsectionexample',
            name='title',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Help Sub-Section Example Title'),
        ),
        migrations.DeleteModel(
            name='Help',
        ),
    ]
