# Generated by Django 2.0.7 on 2018-07-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0005_auto_20180723_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpsection',
            options={'ordering': ['ref_id'], 'verbose_name': 'Help Section', 'verbose_name_plural': 'Help Sections'},
        ),
        migrations.AddField(
            model_name='helpsubsectionexample',
            name='example',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Example'),
        ),
        migrations.AddField(
            model_name='helpsubsectionexample',
            name='instruction',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Instruction'),
        ),
    ]
