# Generated by Django 2.0.7 on 2018-07-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0006_auto_20180723_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpsubsectionexample',
            name='instruction',
        ),
        migrations.AddField(
            model_name='helpsubsection',
            name='instruction',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Instruction'),
        ),
        migrations.AlterField(
            model_name='helpsubsectionexample',
            name='title',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Example Title'),
        ),
    ]
