# Generated by Django 2.0.7 on 2018-07-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0007_auto_20180723_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpsubsection',
            name='links_and_sources',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Links and Sources'),
        ),
    ]
