# Generated by Django 2.0.7 on 2018-07-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0008_helpsubsection_links_and_sources'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helpsubsection',
            old_name='help',
            new_name='help_section',
        ),
    ]
