# Generated by Django 2.0.7 on 2018-07-24 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0009_auto_20180723_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpsubsection',
            name='links_and_sources',
        ),
        migrations.AddField(
            model_name='helpsection',
            name='links_and_sources',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Links and Sources'),
        ),
        migrations.AlterField(
            model_name='helpsubsection',
            name='help_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_help_sections', to='bplanner.HelpSection', verbose_name='Help Section'),
        ),
        migrations.AlterField(
            model_name='helpsubsectionexample',
            name='help_sub_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_help_sub_sections', to='bplanner.HelpSubSection', verbose_name='Help Sub-Section'),
        ),
    ]
