# Generated by Django 2.0.7 on 2018-07-24 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0010_auto_20180724_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpsubsectionexample',
            name='help_sub_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_help_sub_section_examples', to='bplanner.HelpSubSection', verbose_name='Help Sub-Section'),
        ),
    ]
