# Generated by Django 2.0.7 on 2018-07-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0011_auto_20180724_0947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpsection',
            name='links_and_sources',
        ),
    ]
