# Generated by Django 2.0.7 on 2018-07-25 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bplanner', '0012_remove_helpsection_links_and_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name')),
                ('title', models.TextField(blank=True, default='', null=True, verbose_name='Title Page')),
                ('mission_vision', models.TextField(blank=True, default='', null=True, verbose_name='Mission and Page')),
                ('executive_summary', models.TextField(blank=True, default='', null=True, verbose_name='Executive Summary')),
                ('company_description', models.TextField(blank=True, default='', null=True, verbose_name='Company Description')),
                ('key_success_factors', models.TextField(blank=True, default='', null=True, verbose_name='Key Success Factors')),
                ('objectives', models.TextField(blank=True, default='', null=True, verbose_name='Objectives')),
                ('industry_analysis', models.TextField(blank=True, default='', null=True, verbose_name='Industry Analysis')),
                ('tam_sam_som_analysis', models.TextField(blank=True, default='', null=True, verbose_name='TAM-SAM-SOM analysis')),
                ('swot_analysis', models.TextField(blank=True, default='', null=True, verbose_name='SWOT Analysis')),
                ('insights', models.TextField(blank=True, default='', null=True, verbose_name='Insights')),
                ('marketing_plan', models.TextField(blank=True, default='', null=True, verbose_name='Marketing Plan')),
                ('ownership_and_management_plan', models.TextField(blank=True, default='', null=True, verbose_name='Ownership and Management Plan')),
                ('milestones', models.TextField(blank=True, default='', null=True, verbose_name='Milestones')),
                ('finance', models.TextField(blank=True, default='', null=True, verbose_name='Finance')),
                ('references', models.TextField(blank=True, default='', null=True, verbose_name='references')),
                ('date_created', models.DateTimeField(editable=False)),
                ('date_modified', models.DateTimeField(editable=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Business Plan Owner')),
            ],
            options={
                'verbose_name': 'Business Plan',
                'verbose_name_plural': 'Business Plans',
                'ordering': ['-date_modified', '-date_created'],
            },
        ),
    ]
