# Generated by Django 2.0.7 on 2018-07-25 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0013_businessplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessplan',
            old_name='company_description',
            new_name='company_description_page',
        ),
        migrations.RenameField(
            model_name='businessplan',
            old_name='executive_summary',
            new_name='executive_summary_page',
        ),
        migrations.RenameField(
            model_name='businessplan',
            old_name='finance',
            new_name='finance_page',
        ),
        migrations.RenameField(
            model_name='businessplan',
            old_name='industry_analysis',
            new_name='industry_analysis_page',
        ),
        migrations.RenameField(
            model_name='businessplan',
            old_name='insights',
            new_name='insights_page',
        ),
        migrations.RenameField(
            model_name='businessplan',
            old_name='key_success_factors',
            new_name='key_success_factors_page',
        ),
        migrations.RenameField(
            model_name='businessplan',
            old_name='marketing_plan',
            new_name='marketing_plan_page',
        ),
        migrations.RenameField(
            model_name='businessplan',
            old_name='milestones',
            new_name='milestones_page',
        ),
        migrations.RenameField(
            model_name='businessplan',
            old_name='mission_vision',
            new_name='mission_vision_page',
        ),
        migrations.RenameField(
            model_name='businessplan',
            old_name='objectives',
            new_name='objectives_page',
        ),
        migrations.RenameField(
            model_name='businessplan',
            old_name='ownership_and_management_plan',
            new_name='ownership_and_management_plan_page',
        ),
        migrations.RenameField(
            model_name='businessplan',
            old_name='references',
            new_name='references_page',
        ),
        migrations.RenameField(
            model_name='businessplan',
            old_name='swot_analysis',
            new_name='swot_analysis_page',
        ),
        migrations.RenameField(
            model_name='businessplan',
            old_name='tam_sam_som_analysis',
            new_name='tam_sam_som_analysis_page',
        ),
        migrations.RenameField(
            model_name='businessplan',
            old_name='title',
            new_name='title_page',
        ),
    ]
