# Generated by Django 2.0.7 on 2018-07-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0015_auto_20180725_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplan',
            name='date_created',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='businessplan',
            name='date_modified',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
