# Generated by Django 2.0.7 on 2018-07-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0016_auto_20180725_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplan',
            name='name',
            field=models.CharField(default='Missing Name', max_length=500, verbose_name='Name'),
        ),
    ]
