# Generated by Django 2.0.7 on 2018-08-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0017_auto_20180726_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Codes')),
                ('full_name', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('rate_to_dollar', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Rate to Dollar')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
    ]
