# Generated by Django 2.0.7 on 2018-08-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0018_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='Codes')),
                ('full_name', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('order', models.FloatField(blank=True, default=0, null=True, verbose_name='Month order')),
            ],
            options={
                'verbose_name': 'Month',
                'verbose_name_plural': 'Months',
            },
        ),
    ]
