# Generated by Django 2.0.7 on 2018-09-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0019_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessplan',
            name='company_description_page',
        ),
        migrations.RemoveField(
            model_name='businessplan',
            name='executive_summary_page',
        ),
        migrations.RemoveField(
            model_name='businessplan',
            name='finance_page',
        ),
        migrations.RemoveField(
            model_name='businessplan',
            name='industry_analysis_page',
        ),
        migrations.RemoveField(
            model_name='businessplan',
            name='insights_page',
        ),
        migrations.RemoveField(
            model_name='businessplan',
            name='key_success_factors_page',
        ),
        migrations.RemoveField(
            model_name='businessplan',
            name='marketing_plan_page',
        ),
        migrations.RemoveField(
            model_name='businessplan',
            name='milestones_page',
        ),
        migrations.RemoveField(
            model_name='businessplan',
            name='mission_vision_page',
        ),
        migrations.RemoveField(
            model_name='businessplan',
            name='name',
        ),
        migrations.RemoveField(
            model_name='businessplan',
            name='objectives_page',
        ),
        migrations.RemoveField(
            model_name='businessplan',
            name='ownership_and_management_plan_page',
        ),
        migrations.RemoveField(
            model_name='businessplan',
            name='references_page',
        ),
        migrations.RemoveField(
            model_name='businessplan',
            name='swot_analysis_page',
        ),
        migrations.RemoveField(
            model_name='businessplan',
            name='tam_sam_som_analysis_page',
        ),
        migrations.RemoveField(
            model_name='businessplan',
            name='title_page',
        ),
        migrations.AddField(
            model_name='businessplan',
            name='address',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Business address'),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='company_name',
            field=models.CharField(blank=True, default='Missing Name', max_length=500, null=True, verbose_name='Company Name'),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='email',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='financial_assumptions',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Financial Assumptions'),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='financial_input',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Financial Input'),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='logo',
            field=models.ImageField(default='logo_default.png', upload_to='imgs/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='main_content',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Main Content'),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Phone Number'),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='presented_to',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Presented to'),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Tagline'),
        ),
        migrations.AddField(
            model_name='businessplan',
            name='website',
            field=models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Website'),
        ),
    ]
