# Generated by Django 2.0.7 on 2018-09-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0020_auto_20180902_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplan',
            name='logo',
            field=models.ImageField(default='logo_default.png', null=True, upload_to='imgs/', verbose_name='Logo'),
        ),
    ]
