# Generated by Django 2.0.7 on 2018-09-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0021_auto_20180902_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessplan',
            name='company_name',
            field=models.CharField(default='', max_length=500, verbose_name='Company, Business, or Project name'),
        ),
        migrations.AlterField(
            model_name='businessplan',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='businessplan',
            name='date_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Modified'),
        ),
    ]
