# Generated by Django 2.0.7 on 2018-09-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bplanner', '0023_auto_20180903_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessplan',
            name='size',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Size'),
        ),
    ]
